services:

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn
      --bind 0.0.0.0:8000
      config.wsgi:application
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - db
      - redis

  celery:
    build: .
    command:
      - celery
      - -A
      - config.settings.celery
      - worker
      - --loglevel=info
    volumes:
      - .:/app
      - logs_volume:/app/logs
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DATABASE_URL: ${DATABASE_URL}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
  logs_volume: