# Generated by Django 6.0.6 on 2026-07-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_story'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
